import { SubscriptionTier } from '../types/payments';

export const SUBSCRIPTION_PLANS: Record<string, SubscriptionTier> = {
  FREE: {
    id: 'free',
    name: 'Free',
    price: 0,
    features: [
      '✓ 3 workouts per week',
      '✓ Basic exercise library (100 exercises)',
      '✓ Manual nutrition logging',
      '✓ 7-day history',
      '✓ Basic progress tracking',
      '✓ Community access',
    ],
    limitations: {
      workoutsPerWeek: 3,
      exerciseLibrarySize: 100,
      historyDays: 7,
      ariaChatsPerDay: 3,
      wearableSync: false,
      advancedAnalytics: false,
      mealPlanning: false,
      formAnalysis: false,
      customWorkoutPlans: false,
      barcodeScanning: false,
      exportData: false,
      prioritySupport: false,
      groupChallenges: false,
      personalizedProgramming: false,
      coachCheckIns: false,
      supplementGuidance: false,
    },
  },
  PREMIUM_MONTHLY: {
    id: 'premium_monthly',
    name: 'Premium',
    stripePriceId: process.env.STRIPE_PREMIUM_MONTHLY_PRICE_ID || 'price_premium_monthly',
    price: 9.99,
    interval: 'month',
    trial: 7,
    features: [
      '✓ Unlimited workouts',
      '✓ Full exercise library (500+ exercises)',
      '✓ Barcode scanning for nutrition',
      '✓ Advanced analytics & insights',
      '✓ ARIA AI Coach (unlimited chats)',
      '✓ Wearable device sync',
      '✓ Custom workout plans',
      '✓ Meal planning & recipes',
      '✓ Progress photos with overlays',
      '✓ Priority support',
      '✓ Export your data',
      '✓ No ads',
    ],
    limitations: {
      wearableSync: true,
      advancedAnalytics: true,
      mealPlanning: true,
      formAnalysis: false,
      customWorkoutPlans: true,
      barcodeScanning: true,
      exportData: true,
      prioritySupport: true,
      groupChallenges: true,
      personalizedProgramming: false,
      coachCheckIns: false,
      supplementGuidance: false,
    },
  },
  PREMIUM_YEARLY: {
    id: 'premium_yearly',
    name: 'Premium',
    stripePriceId: process.env.STRIPE_PREMIUM_YEARLY_PRICE_ID || 'price_premium_yearly',
    price: 79.99,
    interval: 'year',
    trial: 7,
    savings: '33% off',
    features: [
      '✓ Everything in Premium Monthly',
      '✓ Save $40 per year (33% off)',
      '✓ Lock in your price forever',
      '✓ Exclusive yearly member perks',
    ],
    limitations: {
      wearableSync: true,
      advancedAnalytics: true,
      mealPlanning: true,
      formAnalysis: false,
      customWorkoutPlans: true,
      barcodeScanning: true,
      exportData: true,
      prioritySupport: true,
      groupChallenges: true,
      personalizedProgramming: false,
      coachCheckIns: false,
      supplementGuidance: false,
    },
  },
  ELITE_MONTHLY: {
    id: 'elite_monthly',
    name: 'Elite',
    stripePriceId: process.env.STRIPE_ELITE_MONTHLY_PRICE_ID || 'price_elite_monthly',
    price: 19.99,
    interval: 'month',
    trial: 14,
    features: [
      '✓ Everything in Premium',
      '✓ AI Form analysis with video',
      '✓ Personalized programming',
      '✓ Weekly 1-on-1 coach check-ins',
      '✓ Custom meal plans by nutritionist',
      '✓ Supplement guidance & timing',
      '✓ Private group challenges',
      '✓ Early access to new features',
      '✓ Direct access to fitness experts',
      '✓ Exclusive Elite community',
      '✓ Competition prep support',
      '✓ Recovery & mobility programs',
    ],
    limitations: {
      wearableSync: true,
      advancedAnalytics: true,
      mealPlanning: true,
      formAnalysis: true,
      customWorkoutPlans: true,
      barcodeScanning: true,
      exportData: true,
      prioritySupport: true,
      groupChallenges: true,
      personalizedProgramming: true,
      coachCheckIns: true,
      supplementGuidance: true,
    },
  },
  ELITE_YEARLY: {
    id: 'elite_yearly',
    name: 'Elite',
    stripePriceId: process.env.STRIPE_ELITE_YEARLY_PRICE_ID || 'price_elite_yearly',
    price: 159.99,
    interval: 'year',
    trial: 14,
    savings: '33% off',
    features: [
      '✓ Everything in Elite Monthly',
      '✓ Save $80 per year (33% off)',
      '✓ Annual fitness assessment',
      '✓ Yearly nutrition consultation',
      '✓ VIP event invitations',
    ],
    limitations: {
      wearableSync: true,
      advancedAnalytics: true,
      mealPlanning: true,
      formAnalysis: true,
      customWorkoutPlans: true,
      barcodeScanning: true,
      exportData: true,
      prioritySupport: true,
      groupChallenges: true,
      personalizedProgramming: true,
      coachCheckIns: true,
      supplementGuidance: true,
    },
  },
};

export const FEATURE_FLAGS = {
  UNLIMITED_WORKOUTS: 'unlimited_workouts',
  FULL_EXERCISE_LIBRARY: 'full_exercise_library',
  BARCODE_SCANNING: 'barcode_scanning',
  ADVANCED_ANALYTICS: 'advanced_analytics',
  AI_COACH_UNLIMITED: 'ai_coach_unlimited',
  WEARABLE_SYNC: 'wearable_sync',
  CUSTOM_WORKOUT_PLANS: 'custom_workout_plans',
  MEAL_PLANNING: 'meal_planning',
  FORM_ANALYSIS: 'form_analysis',
  PERSONALIZED_PROGRAMMING: 'personalized_programming',
  COACH_CHECK_INS: 'coach_check_ins',
  SUPPLEMENT_GUIDANCE: 'supplement_guidance',
  GROUP_CHALLENGES: 'group_challenges',
  EXPORT_DATA: 'export_data',
  PRIORITY_SUPPORT: 'priority_support',
  PROGRESS_PHOTOS: 'progress_photos',
  RECOVERY_PROGRAMS: 'recovery_programs',
  COMPETITION_PREP: 'competition_prep',
} as const;

export const PAYWALL_MESSAGES = {
  WORKOUT_LIMIT: {
    title: 'Workout Limit Reached',
    message: 'You\'ve reached your weekly workout limit. Upgrade to Premium for unlimited workouts!',
    cta: 'Unlock Unlimited Workouts',
  },
  AI_CHAT_LIMIT: {
    title: 'Daily AI Chat Limit',
    message: 'You\'ve used all your AI chats for today. Upgrade for unlimited access to ARIA!',
    cta: 'Get Unlimited AI Coaching',
  },
  BARCODE_SCANNING: {
    title: 'Premium Feature',
    message: 'Barcode scanning makes nutrition tracking 10x faster. Upgrade to unlock!',
    cta: 'Enable Barcode Scanning',
  },
  ADVANCED_ANALYTICS: {
    title: 'Unlock Deep Insights',
    message: 'See detailed analytics, trends, and predictions with Premium.',
    cta: 'View Advanced Analytics',
  },
  WEARABLE_SYNC: {
    title: 'Connect Your Devices',
    message: 'Sync with Apple Watch, Fitbit, and more to track everything automatically.',
    cta: 'Enable Device Sync',
  },
  CUSTOM_PLANS: {
    title: 'Personalized Training',
    message: 'Get custom workout plans tailored to your goals and experience.',
    cta: 'Get Custom Plans',
  },
  FORM_ANALYSIS: {
    title: 'Elite Feature',
    message: 'Get AI-powered form analysis with video to perfect your technique.',
    cta: 'Unlock Form Analysis',
  },
  COACH_CHECK_INS: {
    title: 'Personal Coaching',
    message: 'Get weekly 1-on-1 check-ins with certified coaches. Elite members only.',
    cta: 'Get Personal Coaching',
  },
};

export const PROMO_CODES = {
  WELCOME20: {
    code: 'WELCOME20',
    discountType: 'percentage' as const,
    discountAmount: 20,
    validUntil: new Date('2025-12-31'),
    applicableTiers: ['Premium', 'Elite'] as const,
  },
  STUDENT25: {
    code: 'STUDENT25',
    discountType: 'percentage' as const,
    discountAmount: 25,
    applicableTiers: ['Premium', 'Elite'] as const,
  },
  NEWYEAR50: {
    code: 'NEWYEAR50',
    discountType: 'percentage' as const,
    discountAmount: 50,
    validUntil: new Date('2025-01-31'),
    applicableTiers: ['Premium', 'Elite'] as const,
  },
  COMEBACK30: {
    code: 'COMEBACK30',
    discountType: 'percentage' as const,
    discountAmount: 30,
    applicableTiers: ['Premium', 'Elite'] as const,
  },
};

export const TRIAL_PERIODS = {
  PREMIUM: 7,  // 7-day free trial
  ELITE: 14,   // 14-day free trial
};

export const CURRENCY = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  CAD: 'C$',
  AUD: 'A$',
};