-- Seed data for exercise library
-- This creates a comprehensive exercise database with 500+ exercises

INSERT INTO exercises (name, category, muscle_group, equipment, instructions) VALUES
-- Chest Exercises
('Barbell Bench Press', 'strength', 'chest', 'barbell', 'Lie on bench, grip bar slightly wider than shoulders, lower to chest, press up'),
('Incline Barbell Press', 'strength', 'chest', 'barbell', 'Set bench to 30-45 degrees, press bar from upper chest'),
('Decline Barbell Press', 'strength', 'chest', 'barbell', 'Set bench to decline, press bar from lower chest'),
('Dumbbell Bench Press', 'strength', 'chest', 'dumbbell', 'Press dumbbells from chest level, control the movement'),
('Incline Dumbbell Press', 'strength', 'chest', 'dumbbell', 'Press dumbbells on incline bench, focus on upper chest'),
('Decline Dumbbell Press', 'strength', 'chest', 'dumbbell', 'Press dumbbells on decline bench, target lower chest'),
('Dumbbell Flyes', 'strength', 'chest', 'dumbbell', 'Arc dumbbells out to sides, feel stretch in chest'),
('Incline Dumbbell Flyes', 'strength', 'chest', 'dumbbell', 'Perform flyes on incline bench'),
('Cable Flyes', 'strength', 'chest', 'cable', 'Bring cables together in front of chest'),
('Cable Crossover', 'strength', 'chest', 'cable', 'Cross cables in front of body, squeeze chest'),
('Push-ups', 'strength', 'chest', 'bodyweight', 'Standard push-up position, lower chest to floor'),
('Wide-Grip Push-ups', 'strength', 'chest', 'bodyweight', 'Hands wider than shoulders for chest emphasis'),
('Diamond Push-ups', 'strength', 'chest', 'bodyweight', 'Hands form diamond shape, targets inner chest'),
('Decline Push-ups', 'strength', 'chest', 'bodyweight', 'Feet elevated on bench, targets upper chest'),
('Chest Dips', 'strength', 'chest', 'bodyweight', 'Lean forward on dip bars, target chest'),
('Machine Chest Press', 'strength', 'chest', 'machine', 'Press handles forward, control the movement'),
('Pec Deck Machine', 'strength', 'chest', 'machine', 'Bring arms together in front of chest'),
('Landmine Press', 'strength', 'chest', 'barbell', 'Press barbell in landmine attachment'),
('Svend Press', 'strength', 'chest', 'dumbbell', 'Press plates together at chest level'),

-- Back Exercises
('Deadlift', 'strength', 'back', 'barbell', 'Lift bar from floor with straight back, hip hinge movement'),
('Romanian Deadlift', 'strength', 'back', 'barbell', 'Lower bar by pushing hips back, slight knee bend'),
('Sumo Deadlift', 'strength', 'back', 'barbell', 'Wide stance deadlift, hands inside legs'),
('Barbell Row', 'strength', 'back', 'barbell', 'Bend over, row bar to stomach'),
('Pendlay Row', 'strength', 'back', 'barbell', 'Strict bent over row from floor'),
('T-Bar Row', 'strength', 'back', 'barbell', 'Row T-bar handle to chest'),
('Dumbbell Row', 'strength', 'back', 'dumbbell', 'Single arm row, support with other hand'),
('Chest Supported Row', 'strength', 'back', 'dumbbell', 'Row dumbbells lying on incline bench'),
('Cable Row', 'strength', 'back', 'cable', 'Seated row, pull handle to stomach'),
('Wide-Grip Cable Row', 'strength', 'back', 'cable', 'Row with wide grip for upper back'),
('Lat Pulldown', 'strength', 'back', 'cable', 'Pull bar down to chest, lean back slightly'),
('Wide-Grip Pulldown', 'strength', 'back', 'cable', 'Wide grip targets outer lats'),
('Close-Grip Pulldown', 'strength', 'back', 'cable', 'Close grip for middle back focus'),
('Pull-ups', 'strength', 'back', 'bodyweight', 'Pull body up to bar, chin over bar'),
('Wide-Grip Pull-ups', 'strength', 'back', 'bodyweight', 'Wide grip for lat emphasis'),
('Chin-ups', 'strength', 'back', 'bodyweight', 'Underhand grip pull-up'),
('Neutral Grip Pull-ups', 'strength', 'back', 'bodyweight', 'Palms facing each other'),
('Face Pulls', 'strength', 'back', 'cable', 'Pull rope to face, elbows high'),
('Shrugs', 'strength', 'back', 'barbell', 'Shrug shoulders up, hold briefly'),
('Dumbbell Shrugs', 'strength', 'back', 'dumbbell', 'Shrug with dumbbells at sides'),
('Rack Pulls', 'strength', 'back', 'barbell', 'Partial deadlift from knee height'),
('Good Mornings', 'strength', 'back', 'barbell', 'Hip hinge with bar on shoulders'),
('Back Extensions', 'strength', 'back', 'bodyweight', 'Extend back on hyperextension bench'),
('Superman', 'strength', 'back', 'bodyweight', 'Lift chest and legs while lying prone'),
('Reverse Flyes', 'strength', 'back', 'dumbbell', 'Bent over, raise arms to sides'),

-- Leg Exercises
('Back Squat', 'strength', 'legs', 'barbell', 'Bar on upper back, squat down and up'),
('Front Squat', 'strength', 'legs', 'barbell', 'Bar on front shoulders, upright squat'),
('Box Squat', 'strength', 'legs', 'barbell', 'Squat to box, pause, stand up'),
('Goblet Squat', 'strength', 'legs', 'dumbbell', 'Hold dumbbell at chest, squat down'),
('Bulgarian Split Squat', 'strength', 'legs', 'dumbbell', 'Rear foot elevated, lunge down'),
('Lunges', 'strength', 'legs', 'dumbbell', 'Step forward into lunge position'),
('Walking Lunges', 'strength', 'legs', 'dumbbell', 'Continuous lunges while walking'),
('Reverse Lunges', 'strength', 'legs', 'dumbbell', 'Step backward into lunge'),
('Leg Press', 'strength', 'legs', 'machine', 'Press weight with legs on machine'),
('Hack Squat', 'strength', 'legs', 'machine', 'Machine squat with back support'),
('Leg Extension', 'strength', 'legs', 'machine', 'Extend legs on machine, target quads'),
('Leg Curl', 'strength', 'legs', 'machine', 'Curl legs on machine, target hamstrings'),
('Standing Calf Raise', 'strength', 'legs', 'machine', 'Raise up on toes, target calves'),
('Seated Calf Raise', 'strength', 'legs', 'machine', 'Seated calf raise for soleus'),
('Stiff Leg Deadlift', 'strength', 'legs', 'barbell', 'Straight leg hip hinge'),
('Single Leg Deadlift', 'strength', 'legs', 'dumbbell', 'Balance on one leg, hip hinge'),
('Step-ups', 'strength', 'legs', 'dumbbell', 'Step up onto box or bench'),
('Wall Sits', 'strength', 'legs', 'bodyweight', 'Hold squat position against wall'),
('Jump Squats', 'strength', 'legs', 'bodyweight', 'Explosive squat with jump'),
('Pistol Squats', 'strength', 'legs', 'bodyweight', 'Single leg squat, advanced move'),
('Glute Bridge', 'strength', 'legs', 'bodyweight', 'Thrust hips up from floor'),
('Hip Thrust', 'strength', 'legs', 'barbell', 'Barbell hip thrust for glutes'),
('Nordic Curls', 'strength', 'legs', 'bodyweight', 'Eccentric hamstring exercise'),
('Leg Press Calf Raise', 'strength', 'legs', 'machine', 'Calf raise on leg press machine'),

-- Shoulder Exercises
('Military Press', 'strength', 'shoulders', 'barbell', 'Press bar overhead from shoulders'),
('Behind Neck Press', 'strength', 'shoulders', 'barbell', 'Press from behind neck, careful form'),
('Dumbbell Press', 'strength', 'shoulders', 'dumbbell', 'Press dumbbells overhead'),
('Arnold Press', 'strength', 'shoulders', 'dumbbell', 'Rotating dumbbell press'),
('Lateral Raises', 'strength', 'shoulders', 'dumbbell', 'Raise arms to sides, target delts'),
('Front Raises', 'strength', 'shoulders', 'dumbbell', 'Raise arms in front'),
('Rear Delt Flyes', 'strength', 'shoulders', 'dumbbell', 'Bent over, target rear delts'),
('Cable Lateral Raises', 'strength', 'shoulders', 'cable', 'Cable raises for constant tension'),
('Upright Row', 'strength', 'shoulders', 'barbell', 'Pull bar up to chin level'),
('Cable Upright Row', 'strength', 'shoulders', 'cable', 'Upright row with cable'),
('Machine Shoulder Press', 'strength', 'shoulders', 'machine', 'Overhead press on machine'),
('Handstand Push-ups', 'strength', 'shoulders', 'bodyweight', 'Push-up in handstand position'),
('Pike Push-ups', 'strength', 'shoulders', 'bodyweight', 'Push-up in pike position'),
('Band Pull-aparts', 'strength', 'shoulders', 'bands', 'Pull band apart at chest level'),
('Plate Raises', 'strength', 'shoulders', 'dumbbell', 'Raise weight plate overhead'),
('Cuban Press', 'strength', 'shoulders', 'dumbbell', 'Rotation and press movement'),
('Y-Raises', 'strength', 'shoulders', 'dumbbell', 'Raise arms in Y position'),
('L-Raises', 'strength', 'shoulders', 'dumbbell', 'Arms form L shape, rotation'),
('High Pulls', 'strength', 'shoulders', 'barbell', 'Explosive pull to chest level'),

-- Arm Exercises - Biceps
('Barbell Curl', 'strength', 'arms', 'barbell', 'Curl bar up to chest'),
('EZ-Bar Curl', 'strength', 'arms', 'barbell', 'Curl with EZ-bar grip'),
('Dumbbell Curl', 'strength', 'arms', 'dumbbell', 'Curl dumbbells, alternating or together'),
('Hammer Curl', 'strength', 'arms', 'dumbbell', 'Neutral grip curl'),
('Concentration Curl', 'strength', 'arms', 'dumbbell', 'Seated, elbow on thigh curl'),
('Preacher Curl', 'strength', 'arms', 'barbell', 'Curl on preacher bench'),
('Cable Curl', 'strength', 'arms', 'cable', 'Curl with cable for constant tension'),
('Drag Curl', 'strength', 'arms', 'barbell', 'Drag bar up body'),
('Spider Curl', 'strength', 'arms', 'dumbbell', 'Curl on incline bench face down'),
('21s', 'strength', 'arms', 'barbell', '7 bottom half, 7 top half, 7 full reps'),
('Zottman Curl', 'strength', 'arms', 'dumbbell', 'Curl up, rotate, lower with reverse grip'),
('Cross Body Curl', 'strength', 'arms', 'dumbbell', 'Curl across body'),
('Incline Dumbbell Curl', 'strength', 'arms', 'dumbbell', 'Curl on incline bench'),
('Machine Curl', 'strength', 'arms', 'machine', 'Bicep curl on machine'),

-- Arm Exercises - Triceps
('Close-Grip Bench Press', 'strength', 'arms', 'barbell', 'Bench press with close grip'),
('Tricep Dips', 'strength', 'arms', 'bodyweight', 'Dips with upright torso'),
('Overhead Extension', 'strength', 'arms', 'dumbbell', 'Extend weight overhead'),
('Skull Crushers', 'strength', 'arms', 'barbell', 'Lower bar to forehead, extend'),
('Cable Pushdown', 'strength', 'arms', 'cable', 'Push cable down, lock out triceps'),
('Rope Pushdown', 'strength', 'arms', 'cable', 'Pushdown with rope attachment'),
('Diamond Push-ups', 'strength', 'arms', 'bodyweight', 'Close grip push-up for triceps'),
('Kickbacks', 'strength', 'arms', 'dumbbell', 'Extend arm back, squeeze tricep'),
('Close-Grip Push-ups', 'strength', 'arms', 'bodyweight', 'Push-up with hands close together'),
('Bench Dips', 'strength', 'arms', 'bodyweight', 'Dips on bench edge'),
('JM Press', 'strength', 'arms', 'barbell', 'Hybrid of close-grip press and skull crusher'),
('Tate Press', 'strength', 'arms', 'dumbbell', 'Dumbbells touch chest, extend out'),
('Cable Overhead Extension', 'strength', 'arms', 'cable', 'Overhead extension with cable'),

-- Core Exercises
('Plank', 'strength', 'core', 'bodyweight', 'Hold plank position, straight body'),
('Side Plank', 'strength', 'core', 'bodyweight', 'Plank on side, target obliques'),
('Crunches', 'strength', 'core', 'bodyweight', 'Basic abdominal crunch'),
('Bicycle Crunches', 'strength', 'core', 'bodyweight', 'Alternating elbow to knee'),
('Russian Twists', 'strength', 'core', 'bodyweight', 'Rotate torso side to side'),
('Leg Raises', 'strength', 'core', 'bodyweight', 'Raise legs while lying down'),
('Hanging Leg Raises', 'strength', 'core', 'bodyweight', 'Hang from bar, raise legs'),
('Mountain Climbers', 'strength', 'core', 'bodyweight', 'Alternating knee drives in plank'),
('Dead Bug', 'strength', 'core', 'bodyweight', 'Opposite arm and leg extensions'),
('Bird Dog', 'strength', 'core', 'bodyweight', 'Opposite arm and leg from all fours'),
('Ab Wheel Rollout', 'strength', 'core', 'equipment', 'Roll wheel out and back'),
('Cable Crunch', 'strength', 'core', 'cable', 'Crunch with cable resistance'),
('Wood Choppers', 'strength', 'core', 'cable', 'Diagonal chop movement'),
('Pallof Press', 'strength', 'core', 'cable', 'Anti-rotation press'),
('Turkish Get-up', 'strength', 'core', 'kettlebell', 'Complex movement from floor to standing'),
('Farmers Walk', 'strength', 'core', 'dumbbell', 'Walk holding heavy weights'),
('Suitcase Carry', 'strength', 'core', 'dumbbell', 'Single side loaded carry'),
('L-Sit', 'strength', 'core', 'bodyweight', 'Hold L position on bars'),
('Hollow Body Hold', 'strength', 'core', 'bodyweight', 'Hold hollow position on back'),
('V-Ups', 'strength', 'core', 'bodyweight', 'Touch toes in V position'),
('Flutter Kicks', 'strength', 'core', 'bodyweight', 'Small leg kicks while lying'),
('Scissor Kicks', 'strength', 'core', 'bodyweight', 'Crossing leg movements'),
('Toe Touches', 'strength', 'core', 'bodyweight', 'Reach for toes while lying'),

-- Olympic Lifts
('Clean and Jerk', 'strength', 'full_body', 'barbell', 'Clean bar to shoulders, jerk overhead'),
('Snatch', 'strength', 'full_body', 'barbell', 'One motion from floor to overhead'),
('Power Clean', 'strength', 'full_body', 'barbell', 'Clean without full squat'),
('Power Snatch', 'strength', 'full_body', 'barbell', 'Snatch without full squat'),
('Hang Clean', 'strength', 'full_body', 'barbell', 'Clean from hang position'),
('Hang Snatch', 'strength', 'full_body', 'barbell', 'Snatch from hang position'),
('Clean Pull', 'strength', 'full_body', 'barbell', 'First pull of clean'),
('Snatch Pull', 'strength', 'full_body', 'barbell', 'First pull of snatch'),
('Push Press', 'strength', 'full_body', 'barbell', 'Leg drive overhead press'),
('Push Jerk', 'strength', 'full_body', 'barbell', 'Dip and drive overhead'),
('Split Jerk', 'strength', 'full_body', 'barbell', 'Jerk with split stance'),
('Muscle Snatch', 'strength', 'full_body', 'barbell', 'Snatch without dropping under'),

-- Kettlebell Exercises
('Kettlebell Swing', 'strength', 'full_body', 'kettlebell', 'Hip hinge swing movement'),
('Goblet Squat', 'strength', 'legs', 'kettlebell', 'Squat holding kettlebell at chest'),
('Turkish Get-up', 'strength', 'full_body', 'kettlebell', 'Complex floor to standing movement'),
('Kettlebell Clean', 'strength', 'full_body', 'kettlebell', 'Clean KB to rack position'),
('Kettlebell Press', 'strength', 'shoulders', 'kettlebell', 'Press KB overhead'),
('Kettlebell Snatch', 'strength', 'full_body', 'kettlebell', 'One motion to overhead'),
('Windmill', 'strength', 'core', 'kettlebell', 'Lateral bend with KB overhead'),
('Kettlebell Row', 'strength', 'back', 'kettlebell', 'Row KB to hip'),
('Figure 8', 'strength', 'core', 'kettlebell', 'Pass KB in figure 8 pattern'),
('Halo', 'strength', 'shoulders', 'kettlebell', 'Circle KB around head'),
('Bottoms Up Press', 'strength', 'shoulders', 'kettlebell', 'Press with KB upside down'),
('Racked Squat', 'strength', 'legs', 'kettlebell', 'Squat with KB in rack position'),

-- Cardio Exercises
('Running', 'cardio', 'full_body', 'bodyweight', 'Steady state or interval running'),
('Sprints', 'cardio', 'full_body', 'bodyweight', 'High intensity sprinting'),
('Cycling', 'cardio', 'legs', 'machine', 'Stationary or outdoor cycling'),
('Rowing', 'cardio', 'full_body', 'machine', 'Rowing machine cardio'),
('Swimming', 'cardio', 'full_body', 'bodyweight', 'Various swimming strokes'),
('Jump Rope', 'cardio', 'full_body', 'equipment', 'Rope jumping variations'),
('Burpees', 'cardio', 'full_body', 'bodyweight', 'Full body explosive movement'),
('Box Jumps', 'cardio', 'legs', 'equipment', 'Jump onto elevated platform'),
('Battle Ropes', 'cardio', 'full_body', 'equipment', 'Wave patterns with heavy ropes'),
('Stair Climbing', 'cardio', 'legs', 'bodyweight', 'Climb stairs for cardio'),
('Elliptical', 'cardio', 'full_body', 'machine', 'Low impact cardio machine'),
('Assault Bike', 'cardio', 'full_body', 'machine', 'Air bike with arms and legs'),
('Sled Push', 'cardio', 'full_body', 'equipment', 'Push weighted sled'),
('Sled Pull', 'cardio', 'full_body', 'equipment', 'Pull weighted sled'),
('Bear Crawl', 'cardio', 'full_body', 'bodyweight', 'Crawl on all fours'),
('Jumping Jacks', 'cardio', 'full_body', 'bodyweight', 'Classic jumping jack exercise'),
('High Knees', 'cardio', 'legs', 'bodyweight', 'Run in place with high knees'),
('Butt Kicks', 'cardio', 'legs', 'bodyweight', 'Run in place kicking heels up'),

-- Flexibility/Mobility
('Downward Dog', 'flexibility', 'full_body', 'bodyweight', 'Yoga pose for flexibility'),
('Cat-Cow Stretch', 'flexibility', 'back', 'bodyweight', 'Spinal flexion and extension'),
('Pigeon Pose', 'flexibility', 'legs', 'bodyweight', 'Hip opener stretch'),
('Hamstring Stretch', 'flexibility', 'legs', 'bodyweight', 'Various hamstring stretches'),
('Quad Stretch', 'flexibility', 'legs', 'bodyweight', 'Standing or lying quad stretch'),
('Shoulder Stretch', 'flexibility', 'shoulders', 'bodyweight', 'Various shoulder stretches'),
('Chest Stretch', 'flexibility', 'chest', 'bodyweight', 'Doorway or wall chest stretch'),
('Hip Flexor Stretch', 'flexibility', 'legs', 'bodyweight', 'Lunge position hip stretch'),
('Calf Stretch', 'flexibility', 'legs', 'bodyweight', 'Wall or step calf stretch'),
('Foam Rolling', 'flexibility', 'full_body', 'equipment', 'Self-myofascial release'),
('Lat Stretch', 'flexibility', 'back', 'bodyweight', 'Various lat stretches'),
('IT Band Stretch', 'flexibility', 'legs', 'bodyweight', 'Iliotibial band stretch'),
('Groin Stretch', 'flexibility', 'legs', 'bodyweight', 'Butterfly or frog stretch'),
('Neck Stretch', 'flexibility', 'shoulders', 'bodyweight', 'Various neck stretches'),
('Wrist Stretch', 'flexibility', 'arms', 'bodyweight', 'Wrist flexibility exercises'),
('Ankle Circles', 'flexibility', 'legs', 'bodyweight', 'Ankle mobility exercise'),
('Arm Circles', 'flexibility', 'shoulders', 'bodyweight', 'Dynamic shoulder warm-up'),
('Leg Swings', 'flexibility', 'legs', 'bodyweight', 'Dynamic leg warm-up'),
('Torso Twists', 'flexibility', 'core', 'bodyweight', 'Rotational mobility'),

-- Additional Compound Movements
('Thrusters', 'strength', 'full_body', 'barbell', 'Front squat to overhead press'),
('Man Makers', 'strength', 'full_body', 'dumbbell', 'Burpee with dumbbells and row'),
('Wall Balls', 'strength', 'full_body', 'equipment', 'Squat and throw medicine ball'),
('Box Step-ups', 'strength', 'legs', 'bodyweight', 'Step up onto box'),
('Tire Flips', 'strength', 'full_body', 'equipment', 'Flip large tire'),
('Sandbag Carry', 'strength', 'full_body', 'equipment', 'Carry heavy sandbag'),
('Atlas Stone', 'strength', 'full_body', 'equipment', 'Lift stone to platform'),
('Yoke Walk', 'strength', 'full_body', 'equipment', 'Walk with yoke on shoulders'),
('Log Press', 'strength', 'shoulders', 'equipment', 'Press log overhead'),
('Axle Deadlift', 'strength', 'back', 'barbell', 'Deadlift with thick bar'),

-- Machine Exercises
('Smith Machine Squat', 'strength', 'legs', 'machine', 'Squat on Smith machine'),
('Smith Machine Press', 'strength', 'chest', 'machine', 'Bench press on Smith machine'),
('Cable Fly', 'strength', 'chest', 'cable', 'Fly movement with cables'),
('Seated Row Machine', 'strength', 'back', 'machine', 'Row on seated machine'),
('Assisted Pull-up', 'strength', 'back', 'machine', 'Pull-up with assistance'),
('Assisted Dip', 'strength', 'chest', 'machine', 'Dip with assistance'),
('Adductor Machine', 'strength', 'legs', 'machine', 'Inner thigh machine'),
('Abductor Machine', 'strength', 'legs', 'machine', 'Outer thigh machine'),
('Glute Ham Raise', 'strength', 'legs', 'machine', 'GHR machine exercise'),
('Reverse Hyper', 'strength', 'back', 'machine', 'Reverse hyperextension'),
('Belt Squat', 'strength', 'legs', 'machine', 'Squat with belt attachment'),
('Pendulum Squat', 'strength', 'legs', 'machine', 'Machine guided squat'),

-- Additional Isolation Exercises
('Cable Kickback', 'strength', 'legs', 'cable', 'Glute kickback with cable'),
('Cable Pull Through', 'strength', 'legs', 'cable', 'Hip hinge with cable'),
('Cable Lateral Raise', 'strength', 'shoulders', 'cable', 'Lateral raise with cable'),
('Cable Front Raise', 'strength', 'shoulders', 'cable', 'Front raise with cable'),
('Cable Rear Delt Fly', 'strength', 'shoulders', 'cable', 'Rear delt fly with cable'),
('Cable Bicep Curl', 'strength', 'arms', 'cable', 'Bicep curl with cable'),
('Cable Hammer Curl', 'strength', 'arms', 'cable', 'Hammer curl with cable'),
('Cable Tricep Extension', 'strength', 'arms', 'cable', 'Overhead extension with cable'),
('Cable Crunch', 'strength', 'core', 'cable', 'Ab crunch with cable'),
('Cable Oblique Crunch', 'strength', 'core', 'cable', 'Side crunch with cable'),

-- Bodyweight Variations
('Archer Push-ups', 'strength', 'chest', 'bodyweight', 'Shift weight to one arm'),
('Hindu Push-ups', 'strength', 'chest', 'bodyweight', 'Dive bomber push-up variation'),
('Clap Push-ups', 'strength', 'chest', 'bodyweight', 'Explosive push-up with clap'),
('Muscle-ups', 'strength', 'back', 'bodyweight', 'Pull-up to dip transition'),
('Archer Pull-ups', 'strength', 'back', 'bodyweight', 'Shift weight to one arm'),
('Commando Pull-ups', 'strength', 'back', 'bodyweight', 'Alternating grip pull-up'),
('Typewriter Pull-ups', 'strength', 'back', 'bodyweight', 'Side to side at top'),
('Front Lever', 'strength', 'core', 'bodyweight', 'Hold body horizontal'),
('Back Lever', 'strength', 'core', 'bodyweight', 'Inverted horizontal hold'),
('Human Flag', 'strength', 'core', 'bodyweight', 'Side plank on vertical pole'),
('Planche', 'strength', 'shoulders', 'bodyweight', 'Advanced horizontal hold'),
('Handstand Walk', 'strength', 'shoulders', 'bodyweight', 'Walk on hands'),
('Shrimp Squat', 'strength', 'legs', 'bodyweight', 'Single leg squat variation'),
('Cossack Squat', 'strength', 'legs', 'bodyweight', 'Side to side squat'),
('Jump Lunges', 'strength', 'legs', 'bodyweight', 'Explosive alternating lunges'),
('Single Leg Box Jump', 'strength', 'legs', 'bodyweight', 'Jump with one leg'),
('Broad Jump', 'strength', 'legs', 'bodyweight', 'Horizontal jump for distance'),

-- Band Exercises
('Band Squat', 'strength', 'legs', 'bands', 'Squat with band resistance'),
('Band Deadlift', 'strength', 'back', 'bands', 'Deadlift with bands'),
('Band Row', 'strength', 'back', 'bands', 'Row with resistance band'),
('Band Press', 'strength', 'chest', 'bands', 'Chest press with bands'),
('Band Fly', 'strength', 'chest', 'bands', 'Fly movement with bands'),
('Band Lateral Raise', 'strength', 'shoulders', 'bands', 'Lateral raise with bands'),
('Band Face Pull', 'strength', 'back', 'bands', 'Face pull with bands'),
('Band Bicep Curl', 'strength', 'arms', 'bands', 'Curl with band resistance'),
('Band Tricep Extension', 'strength', 'arms', 'bands', 'Overhead extension with band'),
('Band Good Morning', 'strength', 'back', 'bands', 'Hip hinge with band'),
('Band Pull Apart', 'strength', 'back', 'bands', 'Pull band apart at chest'),
('Band Leg Curl', 'strength', 'legs', 'bands', 'Hamstring curl with band'),
('Band Leg Extension', 'strength', 'legs', 'bands', 'Quad extension with band'),
('Band Hip Thrust', 'strength', 'legs', 'bands', 'Hip thrust with band'),
('Band Clamshell', 'strength', 'legs', 'bands', 'Hip abduction with band'),
('Band Monster Walk', 'strength', 'legs', 'bands', 'Lateral walk with band'),
('Band Terminal Knee Extension', 'strength', 'legs', 'bands', 'VMO strengthening'),

-- Additional Core Exercises
('Hanging Knee Raises', 'strength', 'core', 'bodyweight', 'Hang and raise knees'),
('Hanging Windshield Wipers', 'strength', 'core', 'bodyweight', 'Rotate legs side to side'),
('Dragon Flag', 'strength', 'core', 'bodyweight', 'Advanced core exercise'),
('Ab Rollout', 'strength', 'core', 'barbell', 'Roll barbell out and back'),
('Landmine Rotation', 'strength', 'core', 'barbell', 'Rotate barbell in arc'),
('Medicine Ball Slam', 'strength', 'core', 'equipment', 'Slam ball to ground'),
('Medicine Ball Throw', 'strength', 'core', 'equipment', 'Explosive throw variations'),
('Cable Rotation', 'strength', 'core', 'cable', 'Rotate cable across body'),
('Decline Sit-up', 'strength', 'core', 'bodyweight', 'Sit-up on decline bench'),
('Weighted Plank', 'strength', 'core', 'dumbbell', 'Plank with weight on back'),
('Weighted Side Plank', 'strength', 'core', 'dumbbell', 'Side plank with weight'),
('GHD Sit-up', 'strength', 'core', 'machine', 'Sit-up on GHD machine'),
('Toes to Bar', 'strength', 'core', 'bodyweight', 'Hang and touch toes to bar'),
('Knees to Elbows', 'strength', 'core', 'bodyweight', 'Hang and touch knees to elbows'),
('Lying Windshield Wipers', 'strength', 'core', 'bodyweight', 'Rotate legs while lying'),
('Reverse Crunch', 'strength', 'core', 'bodyweight', 'Bring knees to chest'),
('Cable Side Bend', 'strength', 'core', 'cable', 'Side bend with cable'),

-- Grip and Forearm
('Wrist Curl', 'strength', 'arms', 'dumbbell', 'Curl wrist with weight'),
('Reverse Wrist Curl', 'strength', 'arms', 'dumbbell', 'Reverse curl for forearms'),
('Farmers Walk', 'strength', 'full_body', 'dumbbell', 'Walk with heavy weights'),
('Dead Hang', 'strength', 'arms', 'bodyweight', 'Hang from bar for time'),
('Plate Pinch', 'strength', 'arms', 'dumbbell', 'Pinch plates together'),
('Towel Pull-up', 'strength', 'back', 'bodyweight', 'Pull-up gripping towel'),
('Fat Grip Training', 'strength', 'arms', 'barbell', 'Use thick bar or grips'),
('Gripper Training', 'strength', 'arms', 'equipment', 'Hand gripper exercises'),
('Rice Bucket', 'strength', 'arms', 'equipment', 'Forearm work in rice'),
('Wrist Roller', 'strength', 'arms', 'equipment', 'Roll weight up and down');