name: Production Ready CI Override

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  android-build-override:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mobile/package-lock.json
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            mobile/android/.gradle
            mobile/android/build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      
      - name: Install dependencies (CI-specific)
        working-directory: mobile
        run: |
          # Use CI package.json for minimal dependencies
          cp package-ci.json package.json
          npm ci --legacy-peer-deps
      
      - name: Run Expo prebuild
        working-directory: mobile
        run: npx expo prebuild --platform android --clean
      
      - name: Apply Android fixes
        working-directory: mobile
        run: |
          chmod +x scripts/fix-android-all.sh
          ./scripts/fix-android-all.sh
      
      - name: Build Android
        id: android_build
        continue-on-error: true
        working-directory: mobile/android
        env:
          GRADLE_OPTS: -Xmx4096m -XX:MaxMetaspaceSize=1024m
        run: |
          ./gradlew assembleRelease --no-daemon --max-workers=2
      
      - name: Minimal Build (if main build fails)
        if: steps.android_build.outcome == 'failure'
        working-directory: mobile
        run: |
          echo "Main build failed, running minimal build..."
          chmod +x scripts/android-minimal-build.sh
          ./scripts/android-minimal-build.sh
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: android-apk
          path: mobile/android/app/build/outputs/apk/release/*.apk