
name: Environment Health Check

on:
  pull_request:
    types: [opened, reopened, synchronize]  # only run on PRs
  
  # Add manual trigger in case we want to debug from the Actions tab
  workflow_dispatch: {}

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node 20 and install
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
      # failure propagation handled by runner
    - run: npm ci --legacy-peer-deps
      
    - name: Run health check
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        OPENAI_KAI_KEY: ${{ secrets.OPENAI_KAI_KEY }}
        OPENAI_ARIA_KEY: ${{ secrets.OPENAI_ARIA_KEY }}
        ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
      run: node scripts/health-check.js
      continue-on-error: true
      
    - name: Build project
      if: success()
      run: npm run build
      
    - name: Deploy edge functions (smoke test)
      if: success()
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: |
        npm install -g supabase --legacy-peer-deps
        supabase functions deploy --verify-jwt=false --project-ref=xeugyryfvilanoiethum
      continue-on-error: true
      

