
name: Environment Health Check

on:
  pull_request:
    types: [opened, reopened, synchronize]  # only run on PRs
  
  # Add manual trigger in case we want to debug from the Actions tab
  workflow_dispatch: {}

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Run health check
      id: health_check
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_KAI_KEY }}
        OPENAI_ARIA_KEY: ${{ secrets.OPENAI_ARIA_KEY }}
        ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
      run: node scripts/health-check.js
      continue-on-error: true
      
    - name: Build project
      if: success()
      run: npm run build
      
    - name: Deploy edge functions (smoke test)
      if: success()
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: |
        npm install -g supabase --legacy-peer-deps
        supabase functions deploy --verify-jwt=false --project-ref=xeugyryfvilanoiethum
      continue-on-error: true
      
    # Simple notification that just logs the failure (no permission issues)
    - name: Log failure notification
      if: failure()
      run: |
        echo "🚨 Health check failed!"
        echo "Please check the workflow logs at: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        echo "This failure notification is visible in the workflow summary."
      
    # Alternative notification using workflow summary (always works)
    - name: Create workflow summary
      if: failure()
      run: |
        echo "## 🚨 Health Check Failed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The health check workflow has failed. Please review the logs above for specific error details." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Common Issues:" >> $GITHUB_STEP_SUMMARY
        echo "- Environment variables not properly configured" >> $GITHUB_STEP_SUMMARY
        echo "- Supabase edge functions not deployed" >> $GITHUB_STEP_SUMMARY
        echo "- Network connectivity issues" >> $GITHUB_STEP_SUMMARY
        echo "- API key permissions" >> $GITHUB_STEP_SUMMARY
      

