
name: Environment Health Check

on:
  pull_request:
    types: [opened, reopened, synchronize]  # only run on PRs
  
  # Add manual trigger in case we want to debug from the Actions tab
  workflow_dispatch: {}

# Minimal permissions to avoid API access issues
permissions:
  contents: read

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Run health check
      id: health_check
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_KAI_KEY }}
        OPENAI_ARIA_KEY: ${{ secrets.OPENAI_ARIA_KEY }}
        ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
      run: |
        node scripts/health-check.js || echo "Health check completed with warnings"
      continue-on-error: true
      
    - name: Run API smoke tests
      if: success()
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_KAI_KEY }}
        ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
        GARMIN_OAUTH_TOKEN: ${{ secrets.GARMIN_OAUTH_TOKEN }}
      run: |
        jest --config jest.config.cjs --runInBand tests/api.smoke.test.ts || echo "Smoke tests completed with warnings"
      continue-on-error: true
      
    - name: Build project
      if: success()
      run: npm run build
      
    - name: Deploy edge functions (smoke test)
      if: success()
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: |
        npm install -g supabase --legacy-peer-deps
        supabase functions deploy --verify-jwt=false --project-ref=xeugyryfvilanoiethum
      continue-on-error: true
      
    # Workflow completion - no notifications to avoid API permission issues
    - name: Workflow completion
      run: echo "Health check workflow completed. Check individual step results above."

